#!/bin/bash

# Simple Login with SSH.
# $1: Shortcut.

cd ~
homePath=`pwd`
cd - 1>/dev/null

confPath=$homePath"/etc/fad.conf"

if [ "$1" == "" ] ; then
	echo 'Simple Login with SSH.'
	echo '$1: Shortcut.'
elif [ ! -f "$confPath" ] ; then
	echo 'Wrong Config'
else
	user=`sed '/^'$1':User=/!d;s/.*=//' $confPath`
	ip=`sed '/^'$1':IP=/!d;s/.*=//' $confPath`
	port=`sed '/^'$1':Port=/!d;s/.*=//' $confPath`
	identify=`sed '/^'$1':Identify=/!d;s/.*=//' $confPath`
	if [ "$user" == "" ] ; then
		echo Wrong Shortcut
	else
		ssh $user@$ip -p $port -i $identify
	fi
fi
