#!/bin/bash

# only macOS
# mac: `date -r 1500000000 "+%y%m%d_%H%M%S"`
# linux: `date -d @1500000000 "+%y%m%d_%H%M%S"`

# Batch Rename Script.
# rename by modify time.
# eg: 170714_104000

# work path
cd ~/Downloads/_/
workpath=`pwd`

IFS=$'\n'

appendSuffix=$1

num=0
for cur in $workpath/*
do
	num=`expr $num + 1`
	echo $num
	# get file suffix
	suffix=${cur##*.}
    if [ "$suffix" == "$cur" ] ; then
		suffix=""
    else
		suffix="."${suffix}
    fi

	# get modify time
	mtime=`stat -s $cur`
	mtime=${mtime##*st_mtime=}
	mtime=${mtime%%\ *}
	mtimes=`date -r $mtime "+%y%m%d_%H%M%S"`

	# if already existed
	while [ -f ${workpath}/${mtimes}${suffix} ] ; do
		mtime=`expr $mtime + 1`
		mtimes=`date -r $mtime "+%y%m%d_%H%M%S"`
	done

	filename=${mtimes}${appendSuffix}${suffix}
	mv -i $cur ${workpath}/${filename}

	echo $cur
	echo $filename
done
