#!/bin/bash

# $1: file name
# $2: key

defaultPwd=hello
defaultKey=CC5339E4BFFDA4FF3A5395647BE2124E
cd ~
homePath=`pwd`
cd - 1>/dev/null
confPath=${homePath}/etc/tk.conf
tmpKeyPath=${homePath}/etc/.tkof.tmp
suffix=out

# $1 ori file name
# $2 password
takeOff() {
	if [ "$1" != "" -a "$2" != "" -a "${1:0:1}" != "-" ] ; then
		if [ ! -d "$1" ] ; then
			fileGeneral=`hexdump -n 8 -e '16/1 "%02X" ' $1`
			fileGeneral=`echo $fileGeneral`
			outFilename=${1}.${suffix}
		else
			outFilename=${1%\/}.${suffix}
		fi
		if [ "$fileGeneral" == "53616C7465645F5F" ] ; then
			dd if="$1" | openssl des3 -d -k "$2" | tar -xf -
		else
			tar -cf - "$1" | openssl des3 -salt -k "$2" | dd of="$outFilename"
		fi
	fi
}

getKey() {
	timestamp=`date +%s`
	timestamp=`expr $timestamp / 1000`
	md5Key=`md5 -s $defaultKey$timestamp`
	md5Key=${md5Key##*\ }
	
	if [ -f "$tmpKeyPath" ] ; then
		saveMd5Key=`sed '/^save:/!d;s/save://' $tmpKeyPath`
	fi

	if [ "$saveMd5Key" == "$md5Key" ] ; then
		isOk="true"
	else
		read -s -p ":" tmpPwd
		if [ "$tmpPwd" == "$defaultPwd" ] ; then
            isOk="true"
        fi
	fi

	if [ "$isOk" == "true" ] ; then
		echo "save:"$md5Key > $tmpKeyPath
		echo $defaultKey
	else
		rm -rf $tmpKeyPath
	fi
}

cdWorkPath() {
	if [ -f "$confPath" ] ; then
		workpath=`sed '/^workPath=/!d;s/workPath=//' $confPath`
		tmpPath=${workpath#*\~\/}
		if [ "$tmpPath" == "$workpath" ] ; then
			cd $tmpPath
		else
			cd ~
			cd ./${tmpPath}
		fi
		echo `pwd`
	fi
}

groupOff() {
	workpath=`cdWorkPath`
	list=$1
	tmpPwd=`getKey`
    for cur in $list
    do
        tmpPath=${workpath}/${cur}
        tmpPath=${tmpPath%\/*}
        cd $tmpPath
        echo $cur
		if [ -f "${workpath}/${cur}.${suffix}" -o -d "${workpath}/${cur}" ] ; then
			# in
			if [ ! -f "${workpath}/${cur}.${suffix}" -a "$2" != "out" ] ; then
				takeOff ${cur##*\/} $tmpPwd
				if [ -f "${workpath}/${cur}.${suffix}" ] ; then
					rm -rf ${cur##*\/}
				fi  
			# out
			elif [ ! -d "${workpath}/${cur}" -a "$2" != "in" ] ; then
				takeOff ${cur##*\/}.${suffix} $tmpPwd
				if [ -d "${workpath}/${cur}" ] ; then
					rm -rf ${cur##*\/}.${suffix}
				fi
			# conflict
			else
				if [ "$2" == "" ] ; then
					echo ${cur} CONFLICT
				fi
			fi
		else
			echo ${cur} MISSING
		fi
        echo --------------------
    done
}

groupTest() {
	workpath=`cdWorkPath`
	list=$1
	isConflict="(CONFLICT)"
	isMiss="(MISS)"
    echo ori    out name
    for cur in $list
    do
        oriDir="."
        outFile="."
        if [ -d "${workpath}/${cur}" ] ; then
            oriDir="o"
        fi
        if [ -f "${workpath}/${cur}.${suffix}" ] ; then
            outFile="o"
        fi
        echo "$oriDir    $outFile   $cur"
		if [ "$oriDir" == "$outFile" ] ; then
			if [ "$oriDir" == "." ] ; then
				isMiss="${isMiss} $cur"
			elif [ "$oriDir" == "o" ] ; then
				isConflict="${isConflict} $cur"
			fi
		fi
    done
	if [ "$isMiss" != "(MISS)" ] ; then
		echo $isMiss
	fi
	if [ "$isConflict" != "(CONFLICT)" ] ; then
		echo $isConflict
	fi
}

if [ -f "$1" -o -d "$1" ] ; then
	if [ "$2" == "" ] ; then
		key=`getKey`
	else
		key=$2
	fi
	takeOff $1 $key
elif [ "$1" == "-s" ] ; then
	rm -rf $tmpKeyPath
	echo clear temp file.
elif [ "$1" == "-t" -a -f "$confPath" ] ; then
	list=`sed '/^all=/!d;s/all=//' $confPath`
	groupTest "$list"
elif [ "${1:0:1}" == "-" -a -f "$confPath" ] ; then
    list=`sed '/^all=/!d;s/all=//' $confPath`
	if [ "$1" == "-" -o "$1" == "-in" ] ; then
		groupOff "$list" "in"
	elif [ "$1" == "-out" ] ; then
		groupOff "$list" "out"
	else
		typeList=${1:1:${#1}}
		for i in `seq ${#typeList}`
		do
			typeCur=${typeList:$i-1:1}
			list=`sed '/^'$typeCur'=/!d;s/'$typeCur'=//' $confPath`
			groupOff "$list"
		done
	fi
else
	echo 'tkof: illegal option or file name.'
	echo 'usage:	tkof [filename]'
	echo '	tkof [-t]'
fi
